spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
#    url: jdbc:h2:tcp://localhost/~/test
    password:
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true

logging:
  level:
    p6spy: info

#p6spy query logging
decorator:
  datasource:
    p6spy:
      enable-logging: true
